[project]
name = "pyuvcgen"
version = "0.1.0"
description = "Python-based UVM UVC generator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "pyyaml>=6.0.3",
]

[project.scripts]
pyuvcgen = "pyuvcgen.__main__:main"

[build-system]
requires = ["setuptools>=78.1.0", "wheel>=0.45.1"]
build-backend = "setuptools.build_meta"

[[tool.uv.index]]
name = "pyuvcgen"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

