[project]
name = "pyuvcgen"
version = "1.5.6"
description = "Python-based UVM UVC generator"
authors = [
    { name = "cirobermudezmarquez", email = "cirofabian.bermudez@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "pyyaml>=6.0.3",
]

[project.scripts]
pyuvcgen = "pyuvcgen.cli:main"

[build-system]
requires = ["setuptools>=78.1.0", "wheel>=0.45.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
pyuvcgen = [
    "templates/**/*",
    "templates/**/.gitignore",
    "yaml/**/*",
]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[dependency-groups]
dev = [
    "ruff>=0.14.11",
]

[project.urls]
Homepage = "https://github.com/uvmcollab/pyuvcgen"
Repository = "https://github.com/uvmcollab/pyuvcgen"
Issues = "https://github.com/uvmcollab/pyuvcgen/issues"
