##=============================================================================
## [Filename]       Makefile.filter
## [Project]        -
## [Author]         Ciro Bermudez - cirofabian.bermudezmarquez@ba.infn.it
## [Language]       GNU Makefile
## [Created]        March 2025
## [Modified]       -
## [Description]    Makefile to filter logs
## [Notes]          -
## [Status]         stable
## [Revisions]      -
##=============================================================================

# ===============================  VARIABLES  =================================
FILTER_TOOL  := $(SCRIPTS_DIR)/filter/filter.py
FILTER_DIR   := $(ROOT_DIR)/filter
LOGS         := $(LOGS_DIR)/*_simv.log
LOG_INPUT    := $(lastword $(sort $(wildcard $(LOGS))))

# ================================  TARGETS  ==================================

.PHONY: tt
vars-filter: ## FILTER: See filter vars
	@echo -e "$(C_ORA)Filter variables$(NC)"
	@echo -e "LOG_INPUT  = $(LOG_INPUT)"
#______________________________________________________________________________

.PHONY: filter
filter: ## FILTER: Filter logs
	@echo -e "$(C_ORA)FILTER: Filtering logs$(NC)"
	@mkdir -p $(FILTER_DIR)
	$(FILTER_TOOL) -i $(LOG_INPUT) -o $(FILTER_DIR)/spi_uvc_driver.log -s spi_uvc_driver
	$(FILTER_TOOL) -i $(LOG_INPUT) -o $(FILTER_DIR)/spi_uvc_monitor.log -s spi_uvc_monitor
# $(FILTER_TOOL) -i $(LOG_INPUT) -o $(FILTER_DIR)/top_predictor.log -s top_predictor
# $(FILTER_TOOL) -i $(LOG_INPUT) -o $(FILTER_DIR)/top_coverage.log -s top_coverage
# $(FILTER_TOOL) -i $(LOG_INPUT) -o $(FILTER_DIR)/top_scoreboard.log -s top_scoreboard
#______________________________________________________________________________


.PHONY: clean-filter
clean-filter: ## FILTER: Remove filter logs
	@echo -e "$(C_ORA)FILTER: removing filter logs$(NC)"
	rm -rf $(FILTER_DIR)
#______________________________________________________________________________
